### ISSUE TITLE
Upgrade Messages

### ISSUE THREAD

**Issue by namuso** [caneroj1/team-ios#31]
- [x] Writing new messages - from list of contacts or as option on personviewcontroller
- [x] Swipe to delete
- [x] Add new screen to display detailed info on message
- [x] viewing and writing replies
- [ ] Allow special viewing privileges for iPads
- [x] Allow alternating from received messages and sent messages

**Comment by caneroj1** [comment]
what are the special viewing privileges?

**Comment by namuso** [comment]
I'm going to hold off from the special designed view for iPads, maybe I will complete it further down the road, however it's very low priority and not necessary.
